dist: trusty

language: node_js

addons:
  firefox: "latest"

node_js:
- 'lts/*'
- 'node'

before_install:
# Enable user namespace cloning
- "sysctl kernel.unprivileged_userns_clone=1"

install:
- npm ci

script:
- node patch.js
- XAUTHORITY= npm test

cache:
  directories:
  - "$HOME/.npm"
