dist: trusty

language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6

node_js:
- 'lts/*'
- 'node'

install:
- npm ci

script:
- node patch.js
- npm test

cache:
  directories:
  - "$HOME/.npm"
